services:
  - type: web
    name: clothing-store
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn shopping_store.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: DATABASE_URL
        fromDatabase:
          name: clothing_store_77x2
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False

databases:
  - name: clothing_store_77x2
    databaseName: clothing_store_77x2
    user: clothing_store_77x2_user
